export const swaggerOptions = {
    swaggerDefinition: {
      openapi: '3.0.0',
      info: {
        title: 'Express API for Typescript',
        version: '1.0.0',
        description: 'Express API with autogenerated swagger doc',
      },
      servers: [
        {
          url: 'http://localhost:3000',
        },
      ],
    },
    apis: ['./routes/*.ts'], // files containing annotations as above
  };